/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._course;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _course_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

String ch = "sysop";


      

//\uae30\ubcf8\ud0a4
int id = m.ri("id");
if(id == 0) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc788\uc5b4\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
CourseDao course = new CourseDao();

//\ubcc0\uc218
int recommMax = 8;

//\uc815\ubcf4
DataSet info = course.find("id = " + id + "");
if(!info.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\ud3fc\uccb4\ud06c
info.put("course_file_conv", m.encode(info.s("course_file")));
info.put("course_file_url", m.getUploadUrl(info.s("course_file")));
info.put("course_file_ek", m.encrypt(info.s("course_file") + m.time("yyyyMMdd"))); //\uc720\ud6a8\uc131 \uac80\uc0ac

//\ud30c\uc77c\uc0ad\uc81c

if("fdel".equals(m.rs("mode"))) {

    if(!"".equals(info.s("course_file"))) {
        course.item("course_file", "");
        if(course.update("id = " + id)) {
            m.delFileRoot(m.getUploadPath(info.s("course_file")));
        }
    }
    return;
}

//\ud3fc\uccb4\ud06c
f.addElement("course_nm", info.s("course_nm"), "hname:'\uacfc\uc815\uba85', required:'Y'");
f.addElement("course_file", null, "hname:'\uba54\uc778\uc774\ubbf8\uc9c0', allow:'jpg|jpeg|gif|png'");
f.addElement("lesson_day", info.i("lesson_day"), "hname:'\ud559\uc2b5\uc77c\uc218', option:'number', min:'1', required:'Y'");
f.addElement("description", info.s("description"), "hname:'\uacfc\uc815 \uc18c\uac1c'");
f.addElement("start_date", info.s("start_date"), "hname:'\ud559\uc2b5\uc2dc\uc791\uc77c'");
f.addElement("end_date", info.s("end_date"), "hname:'\ud559\uc2b5\uc885\ub8cc\uc77c'");
f.addElement("recomm_yn", info.s("recomm_yn"), "hname:'\ucd94\ucc9c\uacfc\uc815'");
f.addElement("limit_progress", info.i("limit_progress"), "hname:'\uc9c4\ub3c4 \uc218\ub8cc\uae30\uc900', option:'number'");

//\ub4f1\ub85d
if(m.isPost() && f.validate()) {

    if(!"Y".equals(info.s("recomm_yn")) && "Y".equals(f.get("recomm_yn")) && course.findCount("recomm_yn = 'Y' AND status != -1") >= recommMax) {
        m.jsAlert("\ucd94\ucc9c\uacfc\uc815\uc740 \ucd5c\ub300 " + recommMax + "\uac1c\uae4c\uc9c0\ub9cc \ub4f1\ub85d\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.");
        return; // \ud604\uc7ac \ucd94\ucc9c\uc720\ubb34\uac00 y \uac00 \uc544\ub2c8\uace0 \uccb4\ud06c\ud55c \uac12\uc774 y \uc774\uace0 \uacfc\uc815 \ud14c\uc774\ube14\uc5d0\uc11c \ucd94\ucc9c\uacfc\uc815\uc774 8\uac1c \uc774\uc0c1 \uc774\ub77c\uba74
    }
    course.item("course_nm", f.get("course_nm"));
    course.item("lesson_day", f.getInt("lesson_day"));
    course.item("recomm_yn", f.get("recomm_yn", "N"));
    course.item("description", f.get("description"));
    course.item("limit_progress", f.getInt("limit_progress"));
    course.item("reg_date", m.time("yyyyMMddHHmmss"));

    //\ud559\uc2b5\uc77c\uc218
    if(f.getInt("lesson_day") < 1) { m.jsAlert("\ud559\uc2b5\uc77c\uc218\ub294 1\uc77c \uc774\uc0c1 \uc785\ub825\ud574\uc8fc\uc138\uc694."); return; }

    //\uc774\ubbf8\uc9c0 \ud30c\uc77c \uc720\ubb34 \uccb4\ud06c \ud6c4 \uae30\uc874\uc5d0 \uc788\ub294\uac70 \uc0ad\uc81c
    File f1 = f.saveFile("course_file");
    if(null != f1) {
        course.item("course_file", f.getFileName("course_file"));
        if(!"".equals(info.s("course_file")) && new File(m.getUploadPath(info.s("course_file"))).exists()) {
            m.delFileRoot(m.getUploadPath(info.s("course_file")));
        }
    }

    if(!course.update("id = " + id + "")) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

    //\uc774\ub3d9
    m.jsAlert("\uc131\uacf5\uc801\uc73c\ub85c \uc218\uc815\ud588\uc2b5\ub2c8\ub2e4.");
    m.jsReplace("course_modify.jsp?" + m.qs());
    return;
}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("course.course_insert");
p.setVar("p_title", "\uacfc\uc815 \uc815\ubcf4");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));
p.setVar("form_script", f.getScript());

p.setVar(info);
p.setVar("modify", true);
p.setVar("tab_modify", "current");
p.setVar("cid", id);
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/course/course_modify.jsp"), -9027044963683424396L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/course/init.jsp"), 6133038957141066510L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2253010914700824916L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
