/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._main;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _login__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

//\ucc44\ub110
String ch = "sysop";


      

//\ud3fc\uccb4\ud06c
f.addElement("login_id", null, "hname:'\uc544\uc774\ub514', required:'Y'");
f.addElement("passwd", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y'");

//\ubcc0\uc218
String login_id = f.get("login_id");
String passwd = f.get("passwd");

//\uac1d\uccb4
UserDao user = new UserDao();
UserLoginDao userLogin = new UserLoginDao();

//\ub85c\uadf8\uc778
if(m.isPost() && f.validate()) {

    DataSet info;
    passwd = m.encrypt(passwd, "SHA-256");

    //\uc544\uc774\ub514 \ubd88\uc77c\uce58
    info = user.find("login_id = '" + login_id + "'" + " AND user_type IN ('A', 'S')");
    if(!info.next()) {
        m.jsAlert("\uc544\uc774\ub514 \ub610\ub294 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
        return;
    }

    //\ube44\ubc00\ubc88\ud638 \ubd88\uc77c\uce58
    if(!passwd.equals(info.s("passwd"))) {
        if(info.i("fail_cnt") >= 5) m.jsAlert("\ub85c\uadf8\uc778\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud574 \uc8fc\uc2dc\uae38 \ubc14\ub78d\ub2c8\ub2e4.");
        else {
            m.jsAlert("\uc544\uc774\ub514 \ub610\ub294 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
            user.item("fail_cnt", info.i("fail_cnt") + 1);
            if (!user.update("id = " + info.i("id") + "")) m.log("syslogin", "fail_cnt update error");
        }
        return;
    }

    //\uc911\uc9c0 \uc0c1\ud0dc \ub610\ub294 \uc2e4\ud328\ud69f\uc218 \ucd08\uacfc
    if(info.i("status") != 1 || info.i("fail_cnt") >= 5) {
        m.jsAlert("\ub85c\uadf8\uc778\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud574 \uc8fc\uc2dc\uae38 \ubc14\ub78d\ub2c8\ub2e4.");
        return;
    }

    //\uac31\uc2e0
    user.item("conn_date", m.time("yyyyMMddHHmmss"));
    user.item("fail_cnt", 0);
    if(!user.update("id = " + info.i("id") + "")) {
        m.jsAlert("\uac31\uc2e0\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.");
        return;
    }

    //\uc778\uc99d
    auth.put("ID", info.i("id"));
    auth.put("LOGINID", info.s("login_id"));
    auth.put("NAME", info.s("user_nm"));
    auth.put("TYPE", info.s("user_type"));
    auth.save();

    //\ub85c\uadf8
    userLogin.item("user_id", info.i("id"));
    userLogin.item("user_type", "B");
    userLogin.item("login_type", "I");
    userLogin.item("ip_addr", request.getRemoteAddr());
    userLogin.item("device", userLogin.getDeviceType(request.getHeader("user-agent")));
    userLogin.item("log_date", m.time("yyyyMMdd"));
    userLogin.item("reg_date", m.time("yyyyMMddHHmmss"));
    if(!userLogin.insert()) { m.log("login", "log");}

    //\uc774\ub3d9
    m.jsReplace("/sysop/index.jsp", "parent");
    return;
}

//\ucd9c\ub825
p.setLayout("blank");
p.setBody("main.login");
p.setVar("form_script", f.getScript());
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/main/login.jsp"), -3047813096110426443L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/main/init.jsp"), -6704141218581282537L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2253010914700824916L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
