/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._mypage;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _courseuser_0insert__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(Exception ex) { out.print("Overflow file size. - " + ex.getMessage()); return; }

Page p = new Page();
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

//\ubcc0\uc218
int userId = 0;
String loginId = "";
String userName = "";
String userEmail = "";
String userType = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean loginBlock = false;

//\ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "ENTER2022";

if(auth.isValid()) {
    userId = auth.getInt("USERID");
    loginId = auth.getString("LOGINID");
    userName = auth.getString("USERNAME");
    userEmail = auth.getString("EMAIL");
    userType = auth.getString("TYPE");
    loginBlock = true;
}

p.setVar("login_block", loginBlock);
p.setVar("SYS_TITLE", "<ENTER \"_\"> \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd\uc0ac\uc774\ud2b8!");
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userType);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);

      

//\ub85c\uadf8\uc778
if(0 == userId) { auth.loginForm(); return; }

//\ucc44\ub110
String ch = "mypage";

//\uc815\ubcf4-\ud68c\uc6d0
UserDao user = new UserDao();
DataSet uinfo = user.find("id = ? AND status = 1", new Object[] {userId});//\uc218\uc815
if(!uinfo.next()) { m.jsError("\ud574\ub2f9 \ud68c\uc6d0 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }


      

//\uc81c\ud55c
int courseId = m.ri("courseId");
if (courseId == 0 ) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c\ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
CourseDao course = new CourseDao(); //\uacfc\uc815
CourseUserDao courseUser = new CourseUserDao(); //\uc218\uac15\uc0dd
LessonDao lesson = new LessonDao(); //\uac15\uc758
CourseProgressDao courseProgress = new CourseProgressDao(); //\uc9c4\ub3c4


//\ubcc0\uc218
int applyStatus = 0;

//\uacfc\uc815 \uc815\ubcf4(\uacfc\uc815 \uc544\uc774\ub514, \uacfc\uc815\uc0c1\ud0dc)
DataSet courseInfo = course.find("id = " + courseId + " AND status = 1 ");
//if(!courseInfo.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; };

//\uc218\uac15 \uc2e0\uccad \uc774\ub825: \uc218\uac15\uc2e0\uccad \ub418\uc5b4\uc788\ub294\uc9c0, \uc548\ub418\uc5b4\uc788\ub294\uc9c0. courseuser-\ud559\uc2b5\uc885\ub8cc\uc77c(\uc218\uac15\uc0dd-\uc544\uc774\ub514, \ud68c\uc6d0\uc544\uc774\ub514, \uacfc\uc815\uc544\uc774\ub514, \ud559\uc2b5\uc2dc\uc791\uc77c, \ud559\uc2b5\uc885\ub8cc\uc77c / \ud68c\uc6d0\uc544\uc774\ub514&&\uacfc\uc815\uc544\uc774\ub514 )
DataSet courseInsertInfo = courseUser.find(" user_id = " + userId + " AND course_id = " + courseId + " AND status = 1 ", "*" , " end_date DESC ", 1);

if(courseInsertInfo.next()) {};

//0\ubcf4\ub2e4 \ud06c\uba74 -> \uc7ac\uc218\uac15 \uac00\ub2a5
//0\ubcf4\ub2e4 \uc791\uc73c\uba74 -> \uc218\uac15 \ubd88\uac00
applyStatus = m.diffDate("D", courseInsertInfo.s("end_date"), sysToday);

//\uac15\uc758
//DataSet lessonList = lesson.query(
//    " SELECT a.id, a.course_id "
//    + " FROM " + lesson.table + " a "
//    + " JOIN " + course.table + " b "
//    + " ON a.course_id = b.id "
//    + " WHERE b.id = " + courseId + " AND a.status = 1 "
//);
//while(!lessonList.next()) { m.jsError("\ub808\uc2a8 \ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; };


//\uc218\uac15\uc2e0\uccad
if(m.isPost()) {

    //\uc218\uac15 \uc885\ub8cc\uc77c\uc774 \ud604\uc7ac\uc2dc\uac04\uc744 \uae30\uc900\uc73c\ub85c
    if(applyStatus < 0 ) { //\uc218\uac15\uc2e0\uccad\uc774 \ub418\uc5b4\uc788\ub294\uc9c0 \ud655\uc778
        if(m.diffDate("D", courseInsertInfo.s("start_date"), sysToday) < 0 ) { // \ubbf8\ub798 \uc218\uac15\uc608\uc815
            m.jsAlert("\uc120\ud0dd\ud558\uc2e0 \uacfc\uc815\uc740 \uc218\uac15\uc2e0\uccad \ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. " + courseInfo.s("course_nm") + "\uc740 \uc218\uac15 \uc608\uc815\uc778 \uacfc\uc815\uc785\ub2c8\ub2e4.");
            return;
        }
        m.jsAlert("\uc120\ud0dd\ud558\uc2e0 \uacfc\uc815\uc740 \uc218\uac15\uc2e0\uccad \ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. " + courseInfo.s("course_nm") + "\uc740 \ud604\uc7ac \uc218\uac15\uc911\uc778 \uacfc\uc815\uc785\ub2c8\ub2e4.");
        return;//\uacfc\uc815\uc0c1\uc138\ucc3d
    }

    //\uc785\uacfc\ucc98\ub9ac
    if(!courseUser.addUser(userId, courseId)) { m.jsError("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
    
    m.jsReplace("course_list.jsp", "parent");
    return;
}


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/courseuser_insert.jsp"), 4892191794880727520L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/init.jsp"), 3695357507792775531L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), -2671751158375180785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
