/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._mypage;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.regex.Pattern;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(Exception ex) { out.print("Overflow file size. - " + ex.getMessage()); return; }

Page p = new Page();
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

//\ubcc0\uc218
int userId = 0;
String loginId = "";
String userName = "";
String userEmail = "";
String userType = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean loginBlock = false;

//\ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "ENTER2022";

if(auth.isValid()) {
    userId = auth.getInt("USERID");
    loginId = auth.getString("LOGINID");
    userName = auth.getString("USERNAME");
    userEmail = auth.getString("EMAIL");
    userType = auth.getString("TYPE");
    loginBlock = true;
}

p.setVar("login_block", loginBlock);
p.setVar("SYS_TITLE", "<ENTER \"_\"> \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd\uc0ac\uc774\ud2b8!");
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userType);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);

      

//\ub85c\uadf8\uc778
if(0 == userId) { auth.loginForm(); return; }

//\ucc44\ub110
String ch = "mypage";

//\uc815\ubcf4-\ud68c\uc6d0
UserDao user = new UserDao();
DataSet uinfo = user.find("id = ? AND status = 1", new Object[] {userId});//\uc218\uc815
if(!uinfo.next()) { m.jsError("\ud574\ub2f9 \ud68c\uc6d0 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }


      
    
//\uc554\ud638\ud0a4
String ek = m.rs("ek");
String key = m.rs("k");
if(!ek.equals(m.encrypt(key+"_MODIFY"))) { m.jsReplace("modify_verify.jsp"); return; }

String[] uemail = m.split("@", uinfo.s("email"), 2);
String[] mobile = m.split("-", uinfo.s("mobile"), 3);

//\ud3fc\uccb4\ud06c
f.addElement("user_nm", uinfo.s("user_nm"), "hname:'\uc774\ub984', required:'Y'");
f.addElement("email1", uemail[0], "hname:'\uc774\uba54\uc77c', required:'Y'");
f.addElement("email2", uemail[1], "hname:'\uc774\uba54\uc77c', required:'Y'");
f.addElement("mobile1", mobile[0], "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y'");
f.addElement("mobile2", mobile[1], "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y'");
f.addElement("mobile3", mobile[2], "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y'");
f.addElement("email_yn", uinfo.s("email_yn"), "hname:'\uc774\uba54\uc77c\uc218\uc2e0\ub3d9\uc758'");
f.addElement("sms_yn", uinfo.s("sms_yn"), "hname:'SMS\uc218\uc2e0\ub3d9\uc758'");

//\uc218\uc815
if(m.isPost() && f.validate()) {

    //\ubcc0\uc218
    String email = f.glue("@", "email1, email2").toLowerCase();
    String emailYn = f.get("email_yn");
    String smsYn = f.get("sms_yn");

    if("@".equals(email)) email = "";

    //\uc774\uba54\uc77c\ubcc0\uacbd
    if(!email.equals(userEmail)) {
        if(!"".equals(email) && !user.isMail(email)) {
            m.jsAlert("\uc774\uba54\uc77c\uc774 \ud615\uc2dd\uc5d0 \ub9de\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
            return;
        }
        user.item("email", email);
    }

    //\ud734\ub300\uc804\ud654\ubc88\ud638 \ubcc0\uacbd
    String patternMobile = "(\\d{3})(\\d{3,4})(\\d{4})";
    String newMobile = "";
    if(!"".equals(f.get("mobile2")) || !"".equals(f.get("mobile3"))) {
        newMobile = f.get("mobile1") + f.get("mobile2") + f.get("mobile3");
        if(!Pattern.matches(patternMobile, newMobile)) {
            m.jsAlert("\ud734\ub300\uc804\ud654\ubc88\ud638\ub97c \ud655\uc778\ud574\uc8fc\uc138\uc694.");
            m.js("parent.resetPassword();");
            return;
        }
        newMobile = newMobile.replaceAll(patternMobile, "$1-$2-$3");
    } else {
        newMobile = f.get("mobile1");
    }

    user.item("mobile", newMobile);

    if(!uinfo.s("email_yn").equals(f.get("email_yn"))) {
        user.item("email_date", sysToday);
    }
    if(!uinfo.s("sms_yn").equals(f.get("sms_yn"))) {
        user.item("sms_date", sysToday);
    }
    user.item("email_yn", emailYn);
    user.item("sms_yn", smsYn);

    if(!uinfo.s("user_nm").equals(f.get("user_nm"))) {
        user.item("user_nm", f.get("user_nm"));
    }

    if(!user.update("id = " + userId + "")) {
        m.jsAlert("\ud68c\uc6d0\uc815\ubcf4 \uc218\uc815 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4" + user.errMsg);
        return;
    }

    auth.put("USERNAME", f.get("user_nm"));
    auth.save();

    m.jsAlert("\uc131\uacf5\uc801\uc73c\ub85c \ud68c\uc6d0\uc815\ubcf4\ub97c \uc218\uc815\ud588\uc2b5\ub2c8\ub2e4.");
    m.jsReplace("modify.jsp?ek=" + ek + "&k=" + key, "parent");
    return;
}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("mypage.modify");
p.setVar("form_script", f.getScript()); //\ud3fc \uc2a4\ud06c\ub9bd\ud2b8
p.setVar(uinfo);
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/modify.jsp"), -848191670006736352L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("mypage/init.jsp"), 3695357507792775531L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), -2671751158375180785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
