/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._classroom;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _viewer__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(Exception ex) { out.print("Overflow file size. - " + ex.getMessage()); return; }

Page p = new Page();
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

//\ubcc0\uc218
int userId = 0;
String loginId = "";
String userName = "";
String userEmail = "";
String userType = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
boolean loginBlock = false;

//\ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/member/login.jsp";
auth.keyName = "ENTER2022";

if(auth.isValid()) {
    userId = auth.getInt("USERID");
    loginId = auth.getString("LOGINID");
    userName = auth.getString("USERNAME");
    userEmail = auth.getString("EMAIL");
    userType = auth.getString("TYPE");
    loginBlock = true;
}

p.setVar("login_block", loginBlock);
p.setVar("SYS_TITLE", "<ENTER \"_\"> \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd\uc0ac\uc774\ud2b8!");
p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userType);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);

      

//\ub85c\uadf8\uc778
if(0 == userId) { auth.loginForm(); return; }

//\uae30\ubcf8\ud0a4
int cuid = m.ri("cuid");
if(cuid == 0) { m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
UserDao user = new UserDao();
CourseDao course = new CourseDao();
CourseUserDao courseUser = new CourseUserDao();

//\uc815\ubcf4- \uc218\uac15\uc0dd
DataSet cuinfo = courseUser.query(
    "SELECT a.*, c.course_nm, c.course_file, u.id user_id, u.user_nm "
    + " FROM " + courseUser.table + " a "
    + " INNER JOIN " + course.table + " c ON a.course_id = c.id "
    + " INNER JOIN " + user.table + " u ON a.user_id = u.id"
    + " WHERE a.id = " + cuid + " AND a.user_id = '" + userId + "' AND a.status = 1"
);
if(!cuinfo.next()) { m.jsError("\ud574\ub2f9 \uc218\uac15 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\ud3ec\uba67\ud305
cuinfo.put("start_date_conv", m.time("yyyy.MM.dd", cuinfo.s("start_date")));
cuinfo.put("end_date_conv", m.time("yyyy.MM.dd", cuinfo.s("end_date")));
cuinfo.put("progress_ratio", m.nf(cuinfo.d("progress_ratio"), 1));

//\ubcc0\uc218
String courseId = cuinfo.s("course_id");

//\ucc44\ub110
String ch = "classroom";

      

//\uae30\ubcf8\ud0a4
int lid = m.ri("lid");
if(lid == 0) { m.jsErrClose("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c\ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
CourseProgressDao courseProgress = new CourseProgressDao();
LessonDao lesson = new LessonDao();
CourseUserLogDao courseUserLog = new CourseUserLogDao();

//\uc81c\ud55c-\uc218\uac15\uac00\ub2a5\uc5ec\ubd80
if(0 < m.diffDate("D", cuinfo.s("end_date"), sysToday)) { m.jsErrClose("\ud559\uc2b5\uae30\uac04\uc774 \uc544\ub2d9\ub2c8\ub2e4."); return; }

//\ubaa9\ub85d-\uac15\uc758
DataSet info = lesson.query(
    "SELECT a.*"
    + ", p.max_time, p.last_time, p.study_time, p.complete_yn, p.reg_date "
    + " FROM " + lesson.table + " a "
    + " LEFT JOIN " + courseProgress.table + " p ON p.course_user_id = " + cuid + " AND p.lesson_id = a.id "
    + " WHERE a.status = 1 "
    + " AND a.course_id = " + courseId + " "
    + " AND a.id = " + lid + " "
);
if(!info.next()) { m.jsErrClose("\ud574\ub2f9 \uac15\uc758 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uc81c\ud55c
if(1 != info.i("status")) { m.jsErrClose("\uc0ac\uc6a9 \uc911\uc9c0\ub41c \uac15\uc758\uc785\ub2c8\ub2e4."); return; }

//\ud3ec\uba67\ud305
info.put("study_time", 0 != info.i("study_time") ? info.i("study_time") : 0);
info.put("last_time", 0 != info.i("last_time") ? info.i("last_time") : 0);
info.put("max_time", 0 != info.i("max_time") ? info.i("max_time") : 0);
info.put("lesson_nm_conv", m.cutString(info.s("lesson_nm"), 40));
info.put("image_url", cuinfo.s("course_file"));

//\uac15\uc758\uc758 \uc778\uc815\uc2dc\uac04\uc774 0\uc778 \uacbd\uc6b0 \uace7\ubc14\ub85c \uc644\ub8cc\ucc98\ub9ac
if(info.i("complete_time") == 0 && !"Y".equals(info.s("complete_yn"))) {
    info.put("complete_yn", "Y");
    if(!courseProgress.completeProgress(cuid, lid)) { m.jsAlert("\uc644\ub8cc \ucc98\ub9ac \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
}

//\ub85c\uadf8
courseUserLog.item("course_user_id", cuinfo.i("id"));
courseUserLog.item("lesson_id", info.i("id"));
courseUserLog.item("ip_addr", request.getRemoteAddr()); //\uc544\uc774\ud53c\uc8fc\uc18c
courseUserLog.item("device", courseUserLog.getDeviceType("PC")); //\ub2e8\ub9d0\uae30
courseUserLog.item("log_type", "S"); //S: \uc2dc\uc791, E:\uc885\ub8cc
courseUserLog.item("conn_date", m.time("yyyyMMdd")); //\uc811\uc18d\uc77c
courseUserLog.item("reg_date", m.time("yyyyMMddHHmmss")); //\ub4f1\ub85d\uc77c\uc2dc

if(!courseUserLog.insert()) { m.log("viewer", "cuid=" + cuid + "lid=" + lid); }

//\ub3d9\uc601\uc0c1\uacbd\ub85c\ubcf4\uc548
info.put("start_url_conv", "/player/viewer.jsp?lid=" + lid + "&cuid=" + cuid + "&ek=" + m.encrypt(lid + "|" + cuid + "|" + m.time("yyyyMMdd")));

//\ucd9c\ub825
p.setLayout(null);
p.setBody("classroom.viewer");
p.setVar("image_url", info.s("course_file"));
p.setVar("lesson_url", info.s("lesson_url"));
p.setVar("last_time", info.i("last_time"));
p.setVar("start_pos", info.i("last_time"));
p.setVar("max_time", info.i("max_time"));
p.setVar("file_type", "mp4");
p.setVar(info);
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("classroom/viewer.jsp"), -8289142595794031292L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("classroom/init.jsp"), -6638790553243785233L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), -2671751158375180785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
