/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0insert__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      
//
//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

String ch = "sysop";
boolean isSuperAdmin = "S".equals(userType);


      

//\uac1d\uccb4
UserDao user = new UserDao();

//\ubcc0\uc218
boolean isAdmin = "ADMIN".equals(m.rs("mode"));

//\ud3fc\uccb4\ud06c
f.addElement("login_id", null, "hname:'\ub85c\uadf8\uc778\uc544\uc774\ub514', required:'Y'");
f.addElement("passwd", null, "hname: '\ube44\ubc00\ubc88\ud638', required:'Y', minbyte:'8'");
f.addElement("passwd2", null, "hanme: '\ube44\ubc00\ubc88\ud638\ud655\uc778', required:'Y'");
f.addElement("user_nm", null, "hname: '\uc774\ub984', required: 'Y'");
f.addElement("email1", null, "hname: '\uc774\uba54\uc77c', required:'Y', option:'email', glue:'email2', delim:'@'");
f.addElement("email2", null, "hname: '\uc774\uba54\uc77c', required:'Y'");
f.addElement("mobile1", null, "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y', option:'number', minbyte:'3'");
f.addElement("mobile2", null, "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y', option:'number', minbyte:'3'");
f.addElement("mobile3", null, "hname:'\ud734\ub300\uc804\ud654\ubc88\ud638', required:'Y', option:'number', minbyte:'4'");

//\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514 \uc911\ubcf5 \uc54c\ub9bc
if("VERIFY".equals(m.rs("mode"))) {
    String value = m.rs("v");
    if("".equals(value)) {
        return;
    }
    if (0 < user.findCount("login_id = '" + value.toLowerCase() + "'")) {
        out.print("<span class='bad'>\uc774\ubbf8 \uc0ac\uc6a9\uc911\uc778 \uc544\uc774\ub514\uc785\ub2c8\ub2e4.</span>");
    } else {
        out.print("<span class='good'>\uc0ac\uc6a9\ud560 \uc218 \uc788\ub294 \uc544\uc774\ub514\uc785\ub2c8\ub2e4.</span>");
    }
    return;
}

//\ub4f1\ub85d
if(m.isPost() && f.validate()) {

    //\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514 \uc911\ubcf5\uc5ec\ubd80
    if(0 < user.findCount("login_id = '" + f.get("login_id").toLowerCase() + "'")) {
        m.jsAlert("\uc774\ubbf8 \uc0ac\uc6a9 \uc911\uc778 \uc544\uc774\ub514\uc785\ub2c8\ub2e4.");
        return;
    }

    //\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514 \ud615\uc2dd
    if(!f.get("login_id").matches("^[a-zA-Z]{1}[a-zA-Z0-9]{1,19}$")) {
        m.jsAlert("\uc601\ubb38\uc73c\ub85c \uc2dc\uc791\ud558\ub294 2-20\uc790 \uc601\ubb38, \uc22b\uc790 \uc870\ud569\uc744 \uc785\ub825\ud558\uc138\uc694.");
        return;
    }

    //\uc81c\ud55c - \ube44\ubc00\ubc88\ud638
    if(!f.get("passwd").matches("^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[\\W_]).{8,}$")) {
        m.jsAlert("\ube44\ubc00\ubc88\ud638\ub294 \uc601\ubb38, \uc22b\uc790, \ud2b9\uc218\ubb38\uc790 \uc870\ud569 8\uc790 \uc774\uc0c1 \uc785\ub825\ud558\uc138\uc694.");
        return;
    }
    //\uc81c\ud55c - \ube44\ubc00\ubc88\ud638 \uc77c\uce58
    if(!f.get("passwd").equals(f.get("passwd2"))) {
        m.jsAlert("\ub450 \ube44\ubc00\ubc88\ud638\uac00 \uc77c\uce58\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
        return;
    }

    String mobile = f.glue("-", "mobile1, mobile2, mobile3");
    String email = f.glue("@", "email1, email2").toLowerCase();
    if("--".equals(mobile)) mobile = "";
    if("@".equals(email)) email = "";

    user.item("user_type", f.get("user_type"));
    user.item("login_id", f.get("login_id"));
    user.item("passwd", m.encrypt(f.get("passwd"), "SHA-256"));
    user.item("user_nm", f.get("user_nm"));
    user.item("email", email);
    user.item("mobile", mobile);
    user.item("reg_date", m.time("yyyyMMddHHmmss"));
    user.item("status", f.getInt("status"));

    if (!user.insert()) { m.jsAlert("\ub4f1\ub85d\ud558\ub294\uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

    //\uc774\ub3d9
    m.jsAlert("\ub4f1\ub85d\uc774 \uc644\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4.");
    if(isAdmin) {
        m.jsReplace("admin_list.jsp", "parent");
        return;
    } else {
        m.jsReplace("user_list.jsp", "parent");
        return;
    }

}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("user.user_insert");
p.setVar("p_title", "\ud68c\uc6d0\uad00\ub9ac");
p.setVar("ADMIN_BLOCK", isAdmin);
p.setVar("SUPERADMIN_BLOCK", isSuperAdmin);
p.setVar("form_script", f.getScript());

p.setLoop("status_list", m.arr2loop(user.statusList));
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/user_insert.jsp"), 813242267801103261L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/init.jsp"), -578572554680760256L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2253010914700824916L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
