/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0loginid_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

//\ubcc0\uc218
String docRoot = Config.getDocRoot();
String tplRoot = docRoot + "/sysop/html";

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

// \uae30\ubcf8 \uad00\ub9ac\uc790 \uc815\ubcf4
int userId = 0;
String loginId = "";
String userName = "";
String userType = "";

// \ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "ENTER2022BO";
if(auth.isValid()) {
    userId = m.parseInt(auth.getString("ID"));
    loginId = auth.getString("LOGINID");
    userName = auth.getString("NAME");
    userType = auth.getString("TYPE");

} else {
    if(request.getRequestURI().indexOf("/main/login.jsp") == -1) { //\ub85c\uadf8\uc778 \ud398\uc774\uc9c0\uba74 \uc81c\uc678
        m.jsReplace(auth.loginURL, "top");
        return;
    }
}

p.setVar("SYS_TITLE", "[\uad00\ub9ac\uc790] enter \uc624\ud508 \ub354 \uc774\ub7ec\ub2dd \uc0ac\uc774\ud2b8");


      

String ch = "sysop";
boolean isSuperAdmin = "S".equals(userType);


      

//\uae30\ubcf8\ud0a4
String uid = m.rs("uid");
if("".equals(uid)) { m.jsErrClose("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
UserDao user = new UserDao();

//\uc815\ubcf4
DataSet info = user.find("id = " + uid + " AND status != -1");
if(!info.next()) { m.jsAlert("\ud574\ub2f9 \ud68c\uc6d0\uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return;
}

//\ud3fc\uccb4\ud06c
f.addElement("login_id", null, "hname:'\ub85c\uadf8\uc778\uc544\uc774\ub514', required:'Y'");

//\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514
if("VERIFY".equals(m.rs("mode"))) {
    String value = m.rs("v");
    if("".equals(value)) return;
    if (0 < user.findCount("login_id = '" + value.toLowerCase() + "'")) {
        out.print("<span class='bad'>\uc774\ubbf8 \uc0ac\uc6a9\uc911\uc778 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4. \ub2e4\uc2dc \uc785\ub825\ud574\uc8fc\uc138\uc694.</span>");
    } else {
        out.print("<span class='good'>\uc0ac\uc6a9\ud560 \uc218 \uc788\ub294 \ub85c\uadf8\uc778\uc544\uc774\ub514\uc785\ub2c8\ub2e4.</span>");
    }
    return;
}

//\uc218\uc815
if(m.isPost() && f.validate()) {

    //\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514 \uc911\ubcf5\uc5ec\ubd80
    if(0 < user.findCount("login_id = '" + f.get("login_id").toLowerCase() + "'")) {
        m.jsAlert("\uc774\ubbf8 \uc0ac\uc6a9 \uc911\uc778 \uc544\uc774\ub514\uc785\ub2c8\ub2e4.");
        return;
    }

    //\uc81c\ud55c - \ub85c\uadf8\uc778\uc544\uc774\ub514 \ud615\uc2dd
    if(!f.get("login_id").matches("^[a-zA-Z]{1}[a-zA-Z0-9]{1,19}$")) {
        m.jsAlert("\uc601\ubb38\uc73c\ub85c \uc2dc\uc791\ud558\ub294 2-20\uc790 \uc601\ubb38, \uc22b\uc790 \uc870\ud569\uc744 \uc785\ub825\ud558\uc138\uc694.");
        return;
    }

    user.item("login_id", f.get("login_id"));
    if(!user.update("id = " + uid)) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

    //\uc774\ub3d9
    m.jsReplace("user_modify.jsp?id=" + uid, "parent.parent");
    m.js("parent.CloseLayer()");
    return;

}

//\ucd9c\ub825
p.setLayout("poplayer");
p.setBody("user.user_loginid_modify");
p.setVar("p_title", "\uc544\uc774\ub514 \uc218\uc815");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));
p.setVar("form_script", f.getScript());

p.setVar(info);

p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/user_loginid_modify.jsp"), -4565891816336011800L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/init.jsp"), -578572554680760256L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -2757950905718429357L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
